services:
    backend:
        build: backend/.
        env_file:
            - backend/.env
        ports:
            - "8080:8080"

    frontend:
        build: client/.
        ports:
            - "3000:3000"
        depends_on:
            - backend
