# fly.toml app configuration file generated for westernflow-backend on 2024-01-28T14:25:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'westernflow-backend'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[vm]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
