# fly.toml app configuration file generated for westernflow-api on 2024-02-11T18:07:12-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'westernflow-api'
primary_region = 'yyz'

[build]
  dockerfile = "Dockerfile.api"
  build-target = "final"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

