name: CI
on:
    pull_request:
        branches:
            - master
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with: 
                sparse-checkout: client
            - name: Install dependencies
              working-directory: ./client
              run: yarn install
            - name: Lint code
              working-directory: ./client
              run: yarn lint
            - name: Build
              working-directory: ./client
              run: yarn build
